import type { DashboardSnapshot } from './types';

export const dashboardMock: DashboardSnapshot = {
  months: [
    { label: 'Jan', inflow: 19200, outflow: 17350 },
    { label: 'Feb', inflow: 18600, outflow: 17120 },
    { label: 'Mar', inflow: 19340, outflow: 17710 },
    { label: 'Apr', inflow: 18880, outflow: 18140 },
    { label: 'May', inflow: 19550, outflow: 18360 },
  ],
  gates: [
    {
      gateKey: 'hysa-80000',
      label: 'HYSA gate before 2027 Roth re-engagement',
      currentAmount: 46200,
      targetAmount: 80000,
      targetDate: '2026-12-31',
    },
    {
      gateKey: 'tax-safe-harbor',
      label: 'Federal and state safe-harbor reserve',
      currentAmount: 11250,
      targetAmount: 18000,
      targetDate: '2026-09-15',
    },
  ],
  leakageCategories: [
    { name: 'Amazon convenience creep', monthlyBurn: 920, cap: 650 },
    { name: 'Pet services and boarding', monthlyBurn: 610, cap: 475 },
    { name: 'Dining and delivery spillover', monthlyBurn: 1240, cap: 900 },
  ],
  subscriptionAudit: [
    {
      merchant: 'OpenAI',
      subcategory: 'subscriptions_apps',
      householdRole: 'jeff',
      chargeCount: 5,
      monthCount: 5,
      avgAmount: 20,
      monthlyBurn: 20,
      lastChargedOn: '2026-05-04',
    },
    {
      merchant: 'GitHub',
      subcategory: 'subscriptions_apps',
      householdRole: 'jeff',
      chargeCount: 5,
      monthCount: 5,
      avgAmount: 10,
      monthlyBurn: 10,
      lastChargedOn: '2026-05-12',
    },
    {
      merchant: 'Netflix',
      subcategory: 'streaming',
      householdRole: 'joint',
      chargeCount: 5,
      monthCount: 5,
      avgAmount: 22.99,
      monthlyBurn: 22.99,
      lastChargedOn: '2026-05-08',
    },
    {
      merchant: 'Google One',
      subcategory: 'subscriptions_apps',
      householdRole: 'jeff',
      chargeCount: 5,
      monthCount: 5,
      avgAmount: 9.99,
      monthlyBurn: 9.99,
      lastChargedOn: '2026-05-15',
    },
  ],
  reconciliations: [
    {
      accountId: 'acct-beacon-demo',
      accountLabel: 'Beacon · Joint checking',
      accountType: 'checking',
      periodStart: '2026-04-01',
      periodEnd: '2026-04-30',
      statementOpeningBalance: 17200,
      statementClosingBalance: 18150,
      closingBalanceSource: 'metadata_running_balance',
      computedClosingBalance: 18150,
      varianceAmount: 0,
      varianceExplanation: '',
    },
    {
      accountId: 'acct-beacon-demo',
      accountLabel: 'Beacon · Joint checking',
      accountType: 'checking',
      periodStart: '2026-03-01',
      periodEnd: '2026-03-31',
      statementOpeningBalance: 16410,
      statementClosingBalance: 17200,
      closingBalanceSource: 'metadata_running_balance',
      computedClosingBalance: 17200,
      varianceAmount: 0,
      varianceExplanation: '',
    },
    {
      accountId: 'acct-beacon-demo',
      accountLabel: 'Beacon · Joint checking',
      accountType: 'checking',
      periodStart: '2026-02-01',
      periodEnd: '2026-02-28',
      statementOpeningBalance: 15890,
      statementClosingBalance: 16410,
      closingBalanceSource: 'metadata_running_balance',
      computedClosingBalance: 16410,
      varianceAmount: 0,
      varianceExplanation: '',
    },
    {
      accountId: 'acct-chase-demo',
      accountLabel: 'Chase · Credit Card',
      accountType: 'credit_card',
      periodStart: '2026-04-01',
      periodEnd: '2026-04-30',
      statementOpeningBalance: 3982,
      statementClosingBalance: 4435,
      closingBalanceSource: 'balances_toml',
      computedClosingBalance: 4437,
      varianceAmount: -2,
      varianceExplanation: '',
    },
    {
      accountId: 'acct-chase-demo',
      accountLabel: 'Chase · Credit Card',
      accountType: 'credit_card',
      periodStart: '2026-03-01',
      periodEnd: '2026-03-31',
      statementOpeningBalance: 3120,
      statementClosingBalance: 3982,
      closingBalanceSource: 'balances_toml',
      computedClosingBalance: 3982,
      varianceAmount: 0,
      varianceExplanation: '',
    },
  ],
};
