"""A small, complete household fixture for the verify_state tests.

Mirrors the live shapes the checks were written against (as of 2026-09-22),
scaled down: six accounts, June-September 2026, two balanced $5,000 clusters,
three ACCTVERIFY probes and one Axos leg left unpaired, an Ally checkpoint
history with the known 2,400.00 variance on 2026-06-02, IonBank mortgage rows,
and stored monthly / annual summaries generated by the real renderers.

The reconciliation rows, balance anchors and summaries are produced by the real
code paths (``seed_balance_anchors``, ``reconcile_periods``,
``generate_monthly_summary`` / ``generate_annual_summary``) so the stored shapes
are exactly the ones verify_state reads in production. Built from it, every
check passes except the always-informational ones (``balanced_clusters``,
``config_source``, ``as_of_month``).
"""

from __future__ import annotations

import json
import os
import sqlite3
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from liquidity_gate_mcp.annual_summary import generate_annual_summary
from liquidity_gate_mcp.balances import load_balances
from liquidity_gate_mcp.computed_balance import seed_balance_anchors
from liquidity_gate_mcp.config import ServerSettings
from liquidity_gate_mcp.database import DatabaseManager
from liquidity_gate_mcp.models import (
    ReconcilePeriodsRequest,
    UpsertTransactionOverrideRequest,
    VerifyStateRequest,
    VerifyStateResult,
)
from liquidity_gate_mcp.monthly_summary import generate_monthly_summary
from liquidity_gate_mcp.reconciliation import reconcile_periods
from liquidity_gate_mcp.verify_state import verify_state


PROJECT_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_PATH = PROJECT_ROOT / "server" / "templates" / "verify_state.template.toml"

BEACON = "acct-beacon-dp-876321032"
WEBSTER = "acct-webster-checking"
CHASE = "acct-chase-credit-card"
ALLY = "acct-ally-hysa"
SELFHELP = "acct-selfhelp-savings"

LIFE_OF_ACCOUNT_FILE = "SelfHelp_FCU_Rental_Transactions_LifeOfAccount.csv"

ACCOUNTS = (
    (BEACON, "Beacon", "Checking", "checking"),
    (WEBSTER, "Webster", "Checking", "checking"),
    (CHASE, "Chase", "Credit Card", "credit_card"),
    (ALLY, "Ally", "HYSA", "savings"),
    (SELFHELP, "Self-Help FCU", "Rental Savings", "savings"),
)

MORTGAGE_BLOCK = """
[mortgage.ion]
merchant_match         = "IonBank Mortgage"
annual_rate            = 0.04625

[[mortgage.ion.schedule]]
effective_from         = "2026-01-01"
scheduled_payment      = 4044.66
principal_and_interest = 2611.83
escrow                 = 1432.83

[[mortgage.ion.schedule]]
effective_from         = "2026-09-01"
scheduled_payment      = 4102.65
principal_and_interest = 2611.83
escrow                 = 1490.82

[[mortgage.ion.anchor]]
statement_date = "2026-06-17"
balance        = 475016.69

[[mortgage.ion.anchor]]
statement_date = "2026-08-18"
balance        = 472996.26

[[mortgage.ion.anchor]]
statement_date = "2026-09-17"
balance        = 472110.09
"""

BALANCES_TOML = f"""
[opening_balances]
"{BEACON}" = 10000.00
"{WEBSTER}" = 20000.00
"{CHASE}" = 500.00
"{ALLY}" = 10000.00
"{SELFHELP}" = 1000.00

[statement_closings."{ALLY}"]
"2026-06-02" = 12320.00
"2026-07-01" = 12341.00
"2026-08-01" = 13363.00
{MORTGAGE_BLOCK}
"""


@dataclass(frozen=True)
class Row:
    id: str
    account: str
    on: str
    amount: float
    direction: str
    description: str
    category: str
    subcategory: str | None = None
    role: str = "joint"
    lifecycle: str = "recurring"
    merchant: str | None = None
    group: str | None = None


def _beacon_rows() -> list[Row]:
    ion = dict(direction="transfer", description="IONBANK MORTGAGE PMT", category="fixed_obligation",
               subcategory="mortgage", merchant="IonBank Mortgage")
    pay = dict(direction="inflow", description="MOBILE CHECK DEP", category="income",
               subcategory="paycheck", role="jeff", merchant="Jeff Paycheck")
    xfer = dict(direction="transfer", description="ONLINE TRANSFER FROM WEBSTER", category="transfer")
    return [
        Row("b01", BEACON, "2026-06-01", -4044.66, **ion),
        Row("b02", BEACON, "2026-06-25", 5000.00, **xfer),
        Row("b03", BEACON, "2026-06-27", 5000.00, **xfer),
        Row("b04", BEACON, "2026-06-30", 4694.21, **pay),
        Row("b05", BEACON, "2026-07-01", -4044.66, **ion),
        Row("b06", BEACON, "2026-07-10", -1000.00, "transfer", "ALLY BANK $TRANSFER", "transfer",
            group="grp-ally"),
        Row("b07", BEACON, "2026-07-31", 4694.21, **pay),
        Row("b08", BEACON, "2026-08-01", -4044.66, **ion),
        Row("b09", BEACON, "2026-08-06", 5000.00, **xfer),
        Row("b10", BEACON, "2026-08-15", -2000.00, "transfer", "CHASE CREDIT CRD EPAY", "transfer",
            group="grp-chase"),
        Row("b11", BEACON, "2026-08-31", -150.00, "outflow", "WHOLEFDS MKT", "variable_lifestyle",
            "groceries", merchant="Whole Foods"),
        Row("b12", BEACON, "2026-08-31", 4694.21, **pay),
        Row("b13", BEACON, "2026-09-01", -4102.65, **ion),
    ]


def _webster_rows() -> list[Row]:
    payroll = dict(direction="inflow", description="NOVARTIS SERVICE PAYROLL", category="income",
                   subcategory="payroll", role="ashley", merchant="Novartis Payroll")
    xfer = dict(direction="transfer", description="ONLINE TRANSFER TO BEACON", category="transfer")
    # Ids count DOWN through time: a reverse-chronological (Webster-style) export.
    return [
        Row("w12", WEBSTER, "2026-06-12", 3000.00, **payroll),
        Row("w11", WEBSTER, "2026-06-25", -5000.00, **xfer),
        Row("w10", WEBSTER, "2026-06-26", 3000.00, **payroll),
        Row("w09", WEBSTER, "2026-06-27", -5000.00, **xfer),
        Row("w08", WEBSTER, "2026-07-10", 3000.00, **payroll),
        Row("w07", WEBSTER, "2026-07-24", 3000.00, **payroll),
        Row("w06", WEBSTER, "2026-08-03", -5000.00, **xfer),
        Row("w05", WEBSTER, "2026-08-06", -5000.00, **xfer),
        Row("w04", WEBSTER, "2026-08-07", 3000.00, **payroll),
        Row("w03", WEBSTER, "2026-08-21", 3000.00, **payroll),
        Row("w02", WEBSTER, "2026-08-21", 50.00, "inflow", "NOVARTIS 8302 EDI PAYMNT", "income",
            "reimbursement", "ashley", merchant="Novartis EDI"),
        Row("w01", WEBSTER, "2026-08-28", -80.00, "outflow", "SHAKE SHACK", "variable_lifestyle",
            "dining_out", merchant="Shake Shack"),
    ]


def _chase_rows() -> list[Row]:
    spend = dict(direction="outflow", category="variable_lifestyle")
    return [
        Row("c01", CHASE, "2026-06-05", -120.55, description="WHOLEFDS #123", subcategory="groceries",
            merchant="Whole Foods", **spend),
        Row("c02", CHASE, "2026-06-28", -45.00, description="AMAZON MKTPL*AB12", subcategory="amazon",
            merchant="Amazon", **spend),
        Row("c03", CHASE, "2026-07-12", -60.00, description="TST* THE PLACE", subcategory="dining_out",
            merchant="The Place", **spend),
        Row("c04", CHASE, "2026-07-29", -35.00, description="AMC THEATRES", subcategory="entertainment",
            merchant="AMC", **spend),
        Row("c05", CHASE, "2026-08-03", 5000.00, "transfer", "Payment Thank You-Mobile", "transfer"),
        Row("c06", CHASE, "2026-08-15", 2000.00, "transfer", "Payment Thank You - Web", "transfer",
            group="grp-chase"),
        Row("c07", CHASE, "2026-08-20", -10.31, description="TST* CT GENERAL", subcategory="dining_out",
            merchant="CT General", **spend),
        Row("c08", CHASE, "2026-08-20", -10.31, description="TST* CT GENERAL", subcategory="dining_out",
            merchant="CT General", **spend),
        Row("c09", CHASE, "2026-08-29", -30.00, description="UBER TRIP", subcategory="transportation",
            merchant="Uber", **spend),
    ]


def _ally_rows() -> list[Row]:
    interest = dict(direction="inflow", description="Interest Paid", category="income",
                    subcategory="interest", merchant="Ally Interest")
    return [
        Row("a01", ALLY, "2026-02-12", -100.00, "transfer", "AXOS BANK TRANSFER", "transfer"),
        Row("a02", ALLY, "2026-05-31", 20.00, **interest),
        Row("a03", ALLY, "2026-06-30", 21.00, **interest),
        Row("a04", ALLY, "2026-07-10", 1000.00, "transfer", "Requested transfer from JEFFREY A ZYJESKI",
            "transfer", group="grp-ally"),
        Row("a05", ALLY, "2026-07-31", 22.00, **interest),
        Row("a06", ALLY, "2026-08-31", 23.00, **interest),
    ]


def _selfhelp_rows() -> list[Row]:
    rent = dict(direction="inflow", description="Share Deposit", category="rental",
                subcategory="rental_income", role="rental", merchant="140 Kane D5 Rent")
    probe = dict(direction="transfer", description="ALLY BANK ACCTVERIFY | ACH Deposit",
                 category="transfer", role="jeff", lifecycle="one_time")
    return [
        Row("s01", SELFHELP, "2026-06-03", 1295.00, **rent),
        Row("s02", SELFHELP, "2026-07-03", 1295.00, **rent),
        Row("s03", SELFHELP, "2026-07-15", 0.60, **probe),
        Row("s04", SELFHELP, "2026-07-15", 0.46, **probe),
        Row("s05", SELFHELP, "2026-07-15", -1.06, **probe),
        Row("s08", SELFHELP, "2026-07-31", 1.25, "inflow", "| Dividend", "income", "interest",
            "jeff", merchant="Self-Help Dividend"),
        Row("s06", SELFHELP, "2026-08-03", 1295.00, **rent),
        Row("s07", SELFHELP, "2026-09-03", 1295.00, **rent),
    ]


RUNNING_BALANCE_SEEDS = {BEACON: 10000.00, WEBSTER: 20000.00, SELFHELP: 1000.00}


def _file_name(row: Row) -> str:
    month = row.on[:7]
    return {
        BEACON: f"{month}_Beacon_Checking.csv",
        WEBSTER: f"{month}_Webster_Checking.csv",
        CHASE: f"{month}_Chase_Credit_Card.csv",
        ALLY: f"{month}_Ally_HYSA.csv",
        SELFHELP: LIFE_OF_ACCOUNT_FILE,
    }[row.account]


@dataclass
class Fixture:
    settings: ServerSettings
    database: DatabaseManager
    watch_root: Path

    def run(self, **request: Any) -> VerifyStateResult:
        return verify_state(self.settings, self.database, VerifyStateRequest(**request))

    def check(self, key: str, **request: Any):
        result = self.run(checks=[key], **request)
        [check] = result.checks
        return check

    def execute(self, sql: str, params: tuple = ()) -> None:
        connection = self.database.connect()
        try:
            connection.execute(sql, params)
            connection.commit()
        finally:
            connection.close()

    def query(self, sql: str, params: tuple = ()) -> list[sqlite3.Row]:
        connection = self.database.connect(read_only=True)
        try:
            return connection.execute(sql, params).fetchall()
        finally:
            connection.close()

    def insert(self, row: Row, *, running_balance: float | None = None, file: str | None = None) -> None:
        connection = self.database.connect()
        try:
            _insert_row(connection, row, running_balance, file or _file_name(row))
            connection.commit()
        finally:
            connection.close()

    def delete(self, *ids: str) -> None:
        for tx_id in ids:
            self.execute("DELETE FROM transactions WHERE id = ?", (tx_id,))

    def write_config(self, text: str) -> Path:
        path = self.watch_root / "verify_state.toml"
        path.write_text(text, encoding="utf-8")
        return path

    def write_balances(self, text: str) -> None:
        (self.watch_root / "balances.toml").write_text(text, encoding="utf-8")


def _insert_row(
    connection: sqlite3.Connection, row: Row, running_balance: float | None, file: str
) -> None:
    metadata: dict[str, Any] = {}
    if running_balance is not None:
        metadata["running_balance"] = running_balance
    connection.execute(
        """
        INSERT INTO transactions (
          id, account_id, import_batch_id, source_record_key, source_document_name,
          occurred_on, posted_on, description_raw, merchant_normalized, amount, direction,
          currency, primary_category, subcategory, household_role, lifecycle,
          transfer_group_key, statement_period, metadata_json
        ) VALUES (?, ?, 'batch-fixture', ?, ?, ?, ?, ?, ?, ?, ?, 'USD', ?, ?, ?, ?, ?, NULL, ?)
        """,
        (
            row.id, row.account, f"key-{row.id}", file, row.on, row.on, row.description,
            row.merchant, row.amount, row.direction, row.category, row.subcategory, row.role,
            row.lifecycle, row.group, json.dumps(metadata),
        ),
    )


def build_fixture(tmp_path: Path, schema_path: Path) -> Fixture:
    watch_root = tmp_path / "watch"
    watch_root.mkdir()
    database = DatabaseManager(tmp_path / "fixture.db", schema_path)
    database.initialize()
    settings = ServerSettings(
        project_root=PROJECT_ROOT,
        docs_dir=PROJECT_ROOT / "docs",
        tracker_csv_path=PROJECT_ROOT / "docs" / "Spreadsheet_checklist_for_document_tracking.csv",
        master_index_path=PROJECT_ROOT / "docs" / "00_CASH_FLOW_MASTER_INDEX.md",
        project_status_path=PROJECT_ROOT / "docs" / "PROJECT_STATUS.md",
        database_path=database.database_path,
        schema_path=schema_path,
        watch_root=watch_root,
    )
    fixture = Fixture(settings=settings, database=database, watch_root=watch_root)
    today = date.today()

    connection = database.connect()
    try:
        for account_id, institution, name, account_type in ACCOUNTS:
            connection.execute(
                "INSERT INTO accounts (id, institution, account_name, account_type, owner) "
                "VALUES (?, ?, ?, ?, 'joint')",
                (account_id, institution, name, account_type),
            )
        imported_at = datetime.combine(today - timedelta(days=1), datetime.min.time()).isoformat()
        connection.execute(
            "INSERT INTO import_batches (id, source_name, parser_version, imported_at, raw_payload) "
            "VALUES ('batch-fixture', 'fixture', 'test', ?, '{}')",
            (imported_at + "+00:00",),
        )
        for rows in (_beacon_rows(), _webster_rows(), _chase_rows(), _ally_rows(), _selfhelp_rows()):
            balance = RUNNING_BALANCE_SEEDS.get(rows[0].account)
            for row in rows:
                if balance is not None:
                    balance = round(balance + row.amount, 2)
                _insert_row(connection, row, balance, _file_name(row))
        # The live income rules carry direction_filter='inflow' (fixed in Cowork
        # 2026-09-22); the schema's seed rules predate that.
        connection.execute(
            "UPDATE classification_rules SET direction_filter = 'inflow' WHERE primary_category = 'income'"
        )
        connection.commit()
    finally:
        connection.close()

    # One lifecycle-only override, applied (stamps the flag).
    database.upsert_transaction_override(
        UpsertTransactionOverrideRequest(transaction_id="c03", lifecycle="one_time")
    )

    fixture.write_balances(BALANCES_TOML)
    balances = load_balances(watch_root)
    seed_balance_anchors(database, balances)
    reconcile_periods(
        database,
        balances,
        ReconcilePeriodsRequest(period_start=date(2026, 1, 1), period_end=date(2026, 8, 31)),
    )

    for month in (2, 5, 6, 7, 8):
        generate_monthly_summary(
            database, balances.wealth_bridge, 2026, month, watch_root, mortgage=balances.mortgage
        )
    generate_annual_summary(database, balances.wealth_bridge, 2026, watch_root, mortgage=balances.mortgage)

    (watch_root / "STATUS.md").write_text(
        f"# Status\n\n_Last verified: {today.isoformat()}_\n", encoding="utf-8"
    )

    downloaded = datetime(2026, 9, 2, 12, 0).timestamp()
    for name in ("2026-08_Beacon_Checking.csv", "2026-08_Chase_Credit_Card.csv", "2026-08_Webster_Checking.csv"):
        path = watch_root / "exports" / name
        path.parent.mkdir(exist_ok=True)
        path.write_text("Date,Description,Amount\n", encoding="utf-8")
        os.utime(path, (downloaded, downloaded))

    return fixture
